### PR TITLE
Feature/categories admin

### PR DESCRIPTION
**Pull request by Thamtran1125**
Can you review and merge manage admin for me? Thank you

### CODE REVIEW

**Comment by nhanhvasnet** [comment]
What is `Rose/public/admin/assets/chart-master/LICENSE.md`

**Comment by nhanhvasnet** [comment]
What is `Rose/public/admin/assets/chart-master/component.json`?

**Comment by Thamtran1125** [comment]
It belongs to source admin layout

**Comment by Thamtran1125** [comment]
Because I download layout so I make it and manage categories into one feature. It's of feature/categories-admin

**Comment by nhanhvasnet** [comment]
Please don't push if you not sure about it

**Pull request closed without merging**
