### PR TITLE
create migrate database

### PR DESCRIPTION
**Pull request by hoihmy**
create migrate a database, pls review it.

### CODE REVIEW

**Comment by nhanhvasnet** [comment]
Please update read me for `migrate database`

**Comment by hoihmy** [comment]
Ok, I will do right now.

**Comment by hoihmy** [comment]
I already edit README.md file. So, pls review and merge it.

**Comment by nhanhvasnet** [comment]
I don't think it's syntax to migrate the database.

**Comment by nhanhvasnet** [comment]
`php artisan migrate` is enough.

**Comment by nhanhvasnet** [comment]
Where is migration files?

**Pull request merged**
